config/routes.rb
HelloWorld::Application.routes.draw do

  

  resources :clutches do
    resources :posts
    resources :eggs
  end

  match 'characters/:character_id/relationships/edit' => 'relationships#edit', :as => 'edit_character_relationships', via: :get
    
  resources :characters do
    resources :dragons
    resources :pets
    resources :relationships
  end
  
  resources :users
  resources :sessions
  resources :searches
  resources :articles
  
  match 'welcome' => 'articles#welcome', :as => 'welcome', via: :get
  
  root to: 'articles#welcome'
  
  match 'character_groups/:character_type' => 'characters#index', :as => 'character_type', via: :get
  match 'recent_characters' => 'characters#new_created', :as => 'recent_characters', via: :get
  match 'updated_characters' => 'characters#new_updated', :as => 'updated_characters', via: :get
  match 'set_status/:id' => 'characters#set_status', :as => 'set_status', via: [:get, :put]
  match 'approve_character/:id' => 'characters#approve_character', :as => 'approve_character', via: [:get, :put]
  match 'characters/:id/upload_picture' => 'characters#upload_picture', :as => 'upload_picture', via: [:get, :post]
  
  match 'approve_clutch/:id' => 'clutches#approve_clutch', :as => 'approve_clutch', via: [:get, :put]
  match 'start_hatching/:id' => 'clutches#start_hatching', :as => 'start_hatching', via: [:get, :put]
  
  match 'signup' => 'users#new', via: :get
  match 'signin' => 'sessions#new', via: :get
  match 'signout' => 'sessions#destroy', via: :delete
  match 'authenticate' => 'sessions#edit', via: :get
  
  match 'set_password/:id' => 'users#set_password', :as => 'set_password', via: [:get, :put]

  

end

app/models/clutch.rb
class Clutch < ActiveRecord::Base

  belongs_to :user
  
  has_many :eggs
  has_many :posts
  
  scope :display, ->{ where(approved: true) }
  default_scope { order("creature_type ASC")}
  
  validates :dame, presence: true
  validates :creature_type, presence: true
  validates :date_clutched, presence: true
end

app/controllers/clutches_controller.rb
class ClutchesController < ApplicationController
  before_action :set_clutch, only: [:show, :edit, :update, :destroy, :approve_clutch, :start_hatching]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :admin_user, only: [:approve_clutch, :start_hatching]

  # GET /clutches
  # GET /clutches.json
  def index
    @clutches = Clutch.display
  end

  # GET /clutches/1
  # GET /clutches/1.json
  def show
  end

  # GET /clutches/new
  def new
    @clutch = Clutch.new
  end

  # GET /clutches/1/edit
  def edit
  end

  # POST /clutches
  # POST /clutches.json
  def create
    @clutch = Clutch.new(clutch_params)
    @clutch.user_id = current_user.id
    if @clutch.save
      redirect_to @clutch, notice: 'Clutch was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /clutches/1
  # PATCH/PUT /clutches/1.json
  def update
    if @clutch.update(clutch_params)
      redirect_to @clutch, notice: 'Clutch was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /clutches/1
  # DELETE /clutches/1.json
  def destroy
    @clutch.destroy
    redirect_to clutches_url
  end

  # Allows admit to approve a clutch before it becomes visible on site
  def approve_clutch
    @clutch.approved = !@clutch.approved
    if @clutch.save
      redirect_to users_path
    else
      redirect_to users_path, alert: "Error! Failed to Approve!"
    end
  end
  
  # Hatching code
  def start_hatching
    @count = 0
    @posts = @clutch.posts
    @posts.each do |post|
      @count = @count + 5
      UserMailer.delay(run_at: @count.minutes.from_now).hatching_posts(post)
      post.delay(run_at: @count.minutes.from_now).show_post
      @count = @count + 5
      post.eggs.each do |egg|
        @character = Character.find_by(name: egg.character)
        if @character
          UserMailer.delay(run_at: @count.minutes.from_now).new_dragon_email(egg, @character.user)
          @character.delay(run_at: @count.minutes.from_now).impress_to(egg)
        end
      end
    end
    redirect_to clutch_posts_path(@clutch), notice: 'Hatching Started'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_clutch
      @clutch = Clutch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clutch_params
      params.require(:clutch).permit(:dame, :sire, :dame_color, :sire_color, :creature_type, :date_clutched, :date_hatched, :theme)
    end
end

app/helpers/clutches_helper.rb
module ClutchesHelper
end

app/views/clutches/_creature.html.erb
    <h2>About the <%= @clutch.creature_type %></h2>
    
    <% if @clutch.creature_type == "Dragon" %>
    <p>
      <strong>Name:</strong>
      <%= egg.creature_name %>
    </p>
    <% end %>
    
    <p>
      <strong>Color:</strong>
      <%= egg.creature_color %>
    </p>
  
    <p>
      <strong>Appearance:</strong>
      <%= simple_format(egg.creature_appearance) %>
    </p>
  
    <p>
      <strong>Personality:</strong>
      <%= simple_format(egg.creature_personality) %>
    </p>
  
    <p>
      <i><%= "Based on #{egg.inspiration}"%></i>
    </p>
  
    <p>
      <i><%= "Impressed to #{egg.character}"%></i>
    </p>

app/views/clutches/_form.html.erb
<%= form_for(@clutch) do |f| %>
  <% if @clutch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clutch.errors.count, "error") %> prohibited this clutch from being saved:</h2>

      <ul>
      <% @clutch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dame %><br>
    <%= f.text_field :dame %>
  </div>
  <div class="field">
    <%= f.label "Dame's Color" %><br>
    <%= f.select :dame_color, ['Gold', 'Green'] %>
  </div>
  <div class="field">
    <%= f.label :sire %><br>
    <%= f.text_field :sire %>
  </div>
  <div class="field">
    <%= f.label "Sire's Color" %><br>
    <%= f.select :sire_color, ['Bronze', 'Silver', 'Brown', 'Blue'] %>
  </div>
  <div class="field">
    <%= f.label "Type" %><br>
    <%= f.select :creature_type, ['Dragon', 'Firelizard', 'Wher', 'Other'] %>
  </div>
  <div class="field">
    <%= f.label "Clutched" %><br>
    <%= f.date_field :date_clutched %>
  </div>
  <div class="field">
    <%= f.label "Hatched" %><br>
    <%= f.date_field :date_hatched %>
  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clutches/edit.html.erb
<% title "Edit #{@clutch.dame}'s Clutch"%>

<%= render 'form' %>

<%= link_to 'Show', @clutch %> |
<%= link_to 'Back', clutches_path %>

app/views/clutches/index.html.erb
<% title "Hatching Sands"%>

<p>Welcome to our hatching sands! Here you can find out about the clutches of Exile, past and present. Want to add a clutch of your own? Go ahead and click the "New Clutch" link below to fill out the form. So long as it is approved by the BoD, your clutch will show up within a few days.</p>

<% @clutches.group_by(&:creature_type).each do |type, clutches| %>
<table>
  <h2><%= type %></h2>
  <tbody>
    <% clutches.each do |clutch| %>
      <tr>
        <td class="title"><%= link_to clutch.dame, clutch %></td>
        <td class="last_updated"><%= "Clutched: #{clutch.date_clutched}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

<% if signed_in? %>
  <%= link_to 'New Clutch', new_clutch_path %>
<% end %>

app/views/clutches/new.html.erb
<% title "New Clutch"%>

<%= render 'form' %>

<%= link_to 'Back', clutches_path %>

app/views/clutches/show.html.erb
<%= title "#{@clutch.dame}'s Clutch, Clutched #{@clutch.date_clutched}" %>

<center>
<p>
  <strong>Dame:</strong>
  <%= "#{@clutch.dame_color} #{@clutch.dame}" %>
</p>

<p>
  <strong>Sire:</strong>
  <%= "#{@clutch.sire_color} #{@clutch.sire}" %>
</p>

<p>
  <strong>Date clutched:</strong>
  <%= @clutch.date_clutched %>
</p>

<p>
  <strong>Date hatched:</strong>
  <%= @clutch.date_hatched %>
</p>

  <% if @clutch.date_hatched < (Time.now - 1.day) %>
    <p>
      <strong>Clutch Theme:</strong>
      <%= @clutch.theme %>
    </p>
    
  <% elsif signed_in?%>
    <% if is_admin? || is_current_user?(@clutch.user) %>
      <p>
        <strong>Clutch Theme:</strong>
        <%= @clutch.theme %>
      </p>
    <% end %>
  <% end %>

</center>

<br>

<% @clutch.eggs.each do |egg| %>

  <h2>
    <%= egg.name %> 
    <% if signed_in? %>
      <% if is_admin? || is_current_user?(@clutch.user) %>
      <small>( <%= link_to 'Edit', edit_clutch_egg_path(@clutch, egg) %> | <%= link_to 'Delete', clutch_egg_path(@clutch, egg), method: :delete, data: { confirm: 'Are you sure?' } %> )</small>
      <% end %>
    <% end %>
  </h2>
  
  <p>  
    <strong>Description:</strong>
    <%= simple_format(egg.description) %>
  </p>
  
  <% if @clutch.date_hatched < (Time.now - 1.day) %>
    <%= render :partial => 'creature', :locals => {:egg => egg} %>
    
  <% elsif signed_in?%>
    <% if is_admin? || is_current_user?(@clutch.user) %>
      <%= render :partial => 'creature', :locals => {:egg => egg} %>
    <% end %>
  <% end %>
  
  <br><hr>
<% end %>

<center>
  <p>
    <% if signed_in? %>
      <% if is_admin? || is_current_user?(@clutch.user) %>

        |<%= link_to "Edit", edit_clutch_path(@clutch) %> |
        <%= link_to "Add an Egg", new_clutch_egg_path(@clutch) %>
      <% end %>
    <% end %>
    <% if @clutch.creature_type == "Dragon" %>
      |<%= link_to "Hatching Posts", clutch_posts_path(@clutch) %> 
    <% end %>
    |<%= link_to "Back to All Clutches", clutches_path %> |
  </p>
</center>