config/routes.rb
HelloWorld::Application.routes.draw do

  

  resources :clutches do
    resources :posts
    resources :eggs
  end

  match 'characters/:character_id/relationships/edit' => 'relationships#edit', :as => 'edit_character_relationships', via: :get
    
  resources :characters do
    resources :dragons
    resources :pets
    resources :relationships
  end
  
  resources :users
  resources :sessions
  resources :searches
  resources :articles
  
  match 'welcome' => 'articles#welcome', :as => 'welcome', via: :get
  
  root to: 'articles#welcome'
  
  match 'character_groups/:character_type' => 'characters#index', :as => 'character_type', via: :get
  match 'recent_characters' => 'characters#new_created', :as => 'recent_characters', via: :get
  match 'updated_characters' => 'characters#new_updated', :as => 'updated_characters', via: :get
  match 'set_status/:id' => 'characters#set_status', :as => 'set_status', via: [:get, :put]
  match 'approve_character/:id' => 'characters#approve_character', :as => 'approve_character', via: [:get, :put]
  match 'characters/:id/upload_picture' => 'characters#upload_picture', :as => 'upload_picture', via: [:get, :post]
  
  match 'approve_clutch/:id' => 'clutches#approve_clutch', :as => 'approve_clutch', via: [:get, :put]
  match 'start_hatching/:id' => 'clutches#start_hatching', :as => 'start_hatching', via: [:get, :put]
  
  match 'signup' => 'users#new', via: :get
  match 'signin' => 'sessions#new', via: :get
  match 'signout' => 'sessions#destroy', via: :delete
  match 'authenticate' => 'sessions#edit', via: :get
  
  match 'set_password/:id' => 'users#set_password', :as => 'set_password', via: [:get, :put]

  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  after_create :registration_notification
  
  has_many :characters, dependent: :destroy
  has_many :clutches
  
  validates :name, presence: true
  validates :age, presence: true, numericality: { greater_than_or_equal_to: 16 }
  validates :username, presence: true, length: { maximum: 25}, uniqueness: true, format: { without: /\s/ }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }, :if => :should_validate_password?
  attr_accessor :updating_password
  
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end
  
  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end
  
  def to_param
    "#{self.username}"
  end
  
  def should_validate_password?
    updating_password || new_record?
  end
  
  private
  
  def create_remember_token
    self.remember_token = User.encrypt(User.new_remember_token)
  end
  
  def registration_notification
    UserMailer.registration_confirmation(self).deliver
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :set_user, only: [:show, :edit, :update, :destroy, :set_password]
  before_action :signed_in_user, only: [:index, :show, :edit, :update, :destroy, :set_password]
  before_action :correct_user, only: [:edit, :update, :destroy, :set_password]
  before_action :admin_user, only: [:index]
  before_action :check_update_password, only: [:update]

  # GET /users
  def index
    @users = User.all
    @characters = Character.where(approved: false).order("updated_at ASC").includes(:dragon)
    @clutches = Clutch.where(approved: false).order("updated_at ASC")
  end

  # GET /users/1
  def show
    @characters = @user.characters
    respond_to do |format|
      format.html do
        if is_current_user?(@user) || is_admin?
          render :mypage
        else
          @characters = Character.display.where(user: @user)
        end
      end
      format.js
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /users/1
  def update
    if @user.update(user_params)
      redirect_to @user, notice: "User was successfully updated."
    else
      if @user.updating_password
        render action: 'set_password'
      else
        render action: 'edit'
      end
    end
  end

  # DELETE /users/1
  def destroy
    @user.destroy
    redirect_to users_url
  end
  
  def set_password
    unless session[:authenticated]
      redirect_to authenticate_path
    end
    session[:authenticated] = nil
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find_by(username: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :age, :username, :email, :messenger, :password, :password_confirmation)
    end
    
    def check_update_password
      if params[:user][:password]
        @user.updating_password = true
      end
    end
    
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_wrapper">
    <div class="field">
      <%= f.label :name %> (Will not be displayed.)<br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :age %> (Will not be displayed.)<br>
      <%= f.text_field :age %>
    </div>
    <div class="field">
      <%= f.label :username %><br>
      <%= f.text_field :username %>
    </div>
    <div class="field">
      <%= f.label :email %><br>
      <%= f.text_field :email %>
    </div>
    <div class="field">
      <%= f.label :messenger %> (AIM, Trillian, etc...)<br>
      <%= f.text_field :messenger %>
    </div>
    
    <% if @user.new_record? %>
      <%= render :partial => "password", :locals => {:f => f} %>
    <% end %>
    
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/users/_password.html.erb
<div class="field">
  <%= f.label :password %><br>
  <%= f.password_field :password %>
</div>
<div class="field">
  <%= f.label "Confirm Password" %><br>
  <%= f.password_field :password_confirmation %>
</div>

app/views/users/edit.html.erb
<% title "Update Account Information" %>

<%= render 'form' %>

<center>
  Click <%= link_to "here", set_password_path(@user) %> to reset your password.
</center>

app/views/users/index.html.erb
<% title "Users" %>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Date Joined</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.strftime("%b %d, %Y") %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>



<div class="pending_approval">
  <h2>Characters Pending Approval</h2>

  <hr>

  <table class="char_table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Character Type</th>
        <th>Craft</th>
        <th>Rank</th>
        <th>Dragon</th>
        <th>Color</th>
        <th>Last Updated</th>
        <th>Approve</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td id="char_data"><%= link_to character.name, character %></td>
          <td id="char_option"><%= link_to 'Edit', edit_character_path(character.name) %></td>
          <td id="char_data"><%= character.character_type %></td>
          <td id="char_data"><%= character.craft %></td>
          <td id="char_data"><%= character.rank %></td>
          <td id="char_data"><%= character.dragon.name if character.dragon %></td>
          <td id="char_data"><%= character.dragon.color if character.dragon %></td>
          <td id="char_data"><%= character.updated_at.strftime("%b %d, %Y %I:%M %p") %></td>
          <td id="char_option"><%= link_to "Approve", approve_character_path(character.name) %></td>
          <td id="char_option"><%= link_to 'Delete', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br><hr>

  <h2>Clutches Pending Approval</h2>

  <hr>

  <table class="char_table">
    <thead>
      <tr>
        <th>Dame</th>
        <th>Dame's Color</th>
        <th>Type</th>
        <th>Sire</th>
        <th>Sire's Color</th>
        <th>Clutched</th>
        <th>Hatched</th>
        <th>Approve</th>
        <th>Edit</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @clutches.each do |clutch| %>
        <tr>
          <td id="char_data"><%= link_to clutch.dame, clutch %></td>
          <td id="char_data"><%= clutch.dame_color %></td>
          <td id="char_data"><%= clutch.creature_type %></td>
          <td id="char_data"><%= clutch.sire %></td>
          <td id="char_data"><%= clutch.sire_color %></td>
          <td id="char_data"><%= clutch.date_clutched %></td>
          <td id="char_data"><%= clutch.date_hatched %></td>
          <td id="char_option"><%= link_to "Approve", approve_clutch_path(clutch) %></td>
          <td id="char_option"><%= link_to 'Edit', edit_clutch_path(clutch) %></td>
          <td id="char_option"><%= link_to 'Delete', clutch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<div>

<br><hr>

app/views/users/mypage.html.erb
<%= title @user.username %>

<div id="user_data">
  <p>
    <strong>Name:</strong>
    <%= @user.name %>
    <br>
    <strong>Email:</strong>
    <%= @user.email %>
    <br>
    <strong>Messenger:</strong>
    <%= @user.messenger %>
    <br>
    <strong>Character(s):</strong>
    <%= @characters.count %>  
  </p>
</div>

<div class="my_characters">
  <h2>Listing <%= @user.username %>'s Characters</h2>

  <hr>

  <table class="char_table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Edit</th>
        <th>Character Type</th>
        <th>Craft</th>
        <th>Rank</th>
        <th>Dragon</th>
        <th>Color</th>
        <th>PC/NPC</th>
        <th>Status</th>
        <th>Active</th>
        <th>Delete</th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td id="char_data"><%= link_to character.name, character %></td>
          <td id="char_option"><%= link_to 'Edit', edit_character_path(character.name) %></td>
          <td id="char_data"><%= character.character_type %></td>
          <td id="char_data"><%= character.craft %></td>
          <td id="char_data"><%= character.rank %></td>
          <td id="char_data"><%= character.dragon.name if character.dragon %></td>
          <td id="char_data"><%= character.dragon.color if character.dragon %></td>
          <td id="char_data"><%= character.category %></td>
          <td id="char_data">
            <% if character.active %>
              <%= character.approved ? "Approved" : "Approval Pending" %>
            <% else %>
              <%= "Inactive" %>
            <% end %>
          </td>
          <td id="char_option"><%= link_to character.active ? "Set Inactive" : "Reactivate", set_status_path(character.name) %></td>
          <td id="char_option"><%= link_to 'Delete', character, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<div>

<br><hr>

app/views/users/new.html.erb
<% title "Welcome!" %>

<%= render 'form' %>

app/views/users/set_password.html.erb
<% title "Change Password" %>

<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form_wrapper">

    <%= render :partial => "password", :locals => {:f => f} %>

    <div class="actions">
      <%= f.submit "Change Password" %>
    </div>
  </div>
<% end %>

app/views/users/show.html.erb
<% title @user.username %>

<div id="user_data">
  <p>
    <strong>Email:</strong>
    <%= @user.email %>
    <br>
    <strong>Messenger:</strong>
    <%= @user.messenger %>
    <br>
    <strong>Character(s):</strong>
    <%= @characters.count %>  
  </p>
</div>

<div class="button_wrapper">
  <button id="show"> List Characters </button>
</div>

<div class="character_list">
  <h2>Listing <%= @user.username %>'s Characters</h2>

  <hr>

  <table class="char_table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Character Type</th>
        <th>Craft</th>
        <th>Rank</th>
        <th>Dragon</th>
        <th>Color</th>
      </tr>
    </thead>
    <tbody>
      <% @characters.each do |character| %>
        <tr>
          <td id="char_data"><%= link_to character.name, character %></td>
          <td id="char_data"><%= character.character_type %></td>
          <td id="char_data"><%= character.craft %></td>
          <td id="char_data"><%= character.rank %></td>
          <td id="char_data"><%= character.dragon.name if character.dragon %></td>
          <td id="char_data"><%= character.dragon.color if character.dragon %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<div>

<br><hr>