config/routes.rb
HelloWorld::Application.routes.draw do

  

  resources :clutches do
    resources :posts
    resources :eggs
  end

  match 'characters/:character_id/relationships/edit' => 'relationships#edit', :as => 'edit_character_relationships', via: :get
    
  resources :characters do
    resources :dragons
    resources :pets
    resources :relationships
  end
  
  resources :users
  resources :sessions
  resources :searches
  resources :articles
  
  match 'welcome' => 'articles#welcome', :as => 'welcome', via: :get
  
  root to: 'articles#welcome'
  
  match 'character_groups/:character_type' => 'characters#index', :as => 'character_type', via: :get
  match 'recent_characters' => 'characters#new_created', :as => 'recent_characters', via: :get
  match 'updated_characters' => 'characters#new_updated', :as => 'updated_characters', via: :get
  match 'set_status/:id' => 'characters#set_status', :as => 'set_status', via: [:get, :put]
  match 'approve_character/:id' => 'characters#approve_character', :as => 'approve_character', via: [:get, :put]
  match 'characters/:id/upload_picture' => 'characters#upload_picture', :as => 'upload_picture', via: [:get, :post]
  
  match 'approve_clutch/:id' => 'clutches#approve_clutch', :as => 'approve_clutch', via: [:get, :put]
  match 'start_hatching/:id' => 'clutches#start_hatching', :as => 'start_hatching', via: [:get, :put]
  
  match 'signup' => 'users#new', via: :get
  match 'signin' => 'sessions#new', via: :get
  match 'signout' => 'sessions#destroy', via: :delete
  match 'authenticate' => 'sessions#edit', via: :get
  
  match 'set_password/:id' => 'users#set_password', :as => 'set_password', via: [:get, :put]

  

end

app/models/character.rb
class Character < ActiveRecord::Base
  
  belongs_to :user
  
  has_many :pets
  has_one :dragon, dependent: :destroy, foreign_key: :rider_id
  
  has_many :relationships, dependent: :destroy
  has_many :relatives, through: :relationships
  has_many :inverse_relationships, :class_name => "Relationship", foreign_key: :relative_id, dependent: :destroy
  has_many :inverse_relatives, through: :inverse_relationships, source: :character
  
  validates :name, presence: true, uniqueness: true
  validates :character_type, presence: true
  
  default_scope { order("name ASC")}
  
  scope :recent, ->{ where("created_at > ?", 2.weeks.ago) }
  scope :updated, ->{ where("updated_at > ?", 2.weeks.ago) }
  scope :display, ->{ where(approved: true, active: true) }
  scope :non_rider, ->{ where.not(character_type: "Dragonrider") }
  
  def has_dragon?
    if self.dragon
      true
    else
      false
    end
  end
  
  def to_param
    "#{self.name}"
  end
  
  def impress_to(egg)
    unless self.dragon
      self.create_dragon({name: egg.creature_name, color: egg.creature_color, age: 0, description: egg.creature_appearance, personality: egg.creature_personality})
      self.character_type = "Weyrling"
      self.rank = "Weyrling"
      self.save
    end
  end
  
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  
  before_action :set_character, only: [:show, :edit, :update, :destroy, :set_status, :approve_character, :upload_picture]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy, :set_status]
  before_action :correct_user, only: [:edit, :update, :destroy, :set_status, :upload_picture]
  before_action :admin_user, only: [:approve_character]
  
  helper_method :sort_column, :sort_direction
  
  # GET /characters
  # GET /characters.json
  def index
    if params[:character_type] == "Wings"
      @characters = Character.display.where(character_type: "Dragonrider").order(sort_column + " " + sort_direction).includes(:dragon)
    elsif params[:character_type]
      @characters = Character.display.where(character_type: params[:character_type]).order(sort_column + " " + sort_direction).includes(:dragon)
    else
      @characters = Character.display.order(sort_column + " " + sort_direction).includes(:dragon)
    end
  end

  # GET /characters/1
  # GET /characters/1.json
  def show
  end

  # GET /characters/new
  def new
    @character = Character.new
  end

  # GET /characters/1/edit
  def edit
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(character_params)
    @character.user_id = current_user.id
    if params[:preview_button] || !@character.save
      render action: 'new'
    else
      UserMailer.character_confirmation(@character).deliver
      redirect_to @character, notice: 'Character was successfully created.'
    end
  end

  # PATCH/PUT /characters/1
  # PATCH/PUT /characters/1.json
  def update
    if @character.update(character_params)
      redirect_to @character, notice: 'Character was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character.destroy
    redirect_to user_path(@character.user)
  end
  
  def new_created
    @characters = Character.display.recent.order(sort_column + " " + sort_direction)
  end
  
  def new_updated
    @characters = Character.display.updated.order(sort_column + " " + sort_direction)
  end
  
  def set_status
    @character.active = !@character.active
    if @character.save
      redirect_to user_path(current_user)
    else
      redirect_to user_path(current_user), alert: "Error! Action failed!"
    end
  end
  
  def approve_character
    @character.approved = !@character.approved
    if @character.save
      UserMailer.character_approved(@character).deliver
      redirect_to users_path
    else
      redirect_to users_path, alert: "Error! Failed to Approve!"
    end
  end
  
  def upload_picture
    if params[:picture]
      upload!
      if @character.save
        redirect_to upload_picture_path(@character), notice: "Image successfully uploaded!"
      else
        redirect_to upload_picture_path(@character), alert: "Error! Failed to Upload Image"
      end
    end
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_character
      @character = Character.find_by(name: params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def character_params
      params.require(:character).permit(:category, :name, :pronunciation, :age, :character_type, :rank, :gender, :preference, :location, :description, :personality, :history, :abilities, :dragon_preference, :dragon_names, :craft, :craft_rank, :craft_specialty, :craft_abilities, :hold, :hold_size)
    end
    
    def upload!
      uploaded_io = params[:picture]
      if uploaded_io
        file = "character_#{@character.id}.jpg"
        AWS::S3::S3Object.store(file, uploaded_io.read, ENV["AWS_BUCKET"], :access => :public_read)
        @character.picture = "https://s3.amazonaws.com/#{ENV["AWS_BUCKET"]}/character_#{@character.id}.jpg"
      end
    end
    
    def sort_column
      Character.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
    
end

app/helpers/characters_helper.rb
module CharactersHelper
  
  def map_relationships(relationships)
    relatives = relationships.map do |relationship| 
      link_to relationship.relative.name, character_path(relationship.relative)
    end
    relatives.join(", ").html_safe
  end
end

app/views/characters/_character.html.erb
<p>
  <center>
    <strong>User:</strong>
    <%= link_to @character.user.username, user_path(@character.user) %>
    <% if @character.picture %>
      <br><br>
      <%= image_tag(@character.picture) %>
    <% end %>
  </center>
  <% if @character.pronunciation %>
    <strong>Name Pronounced:</strong>
    <%= @character.pronunciation %>
    <br>
  <% end %>
  <strong>Age:</strong>
  <%= @character.age %>
  <br>
  <strong>Gender:</strong>
  <%= @character.gender %>
  <br>
  <strong>Sexual Orientation:</strong>
  <%= @character.preference %>
  <br>
  <strong>Character Type:</strong>
  <%= @character.character_type %>
  <br>
  <strong>Rank:</strong>
  <%= @character.rank %>
  <br>
  <strong>Location:</strong>
  <%= @character.location %>
</p>

<p>
  <strong>Appearance:</strong>
  <%= simple_format(@character.description) %>
</p>

<p>
  <strong>Personality:</strong>
  <%= simple_format(@character.personality) %>
</p>

<p>
  <strong>History:</strong>
  <%= simple_format(@character.history) %>
</p>

<p>
  <strong>Abilities/Strengths/Weaknesses:</strong>
  <%= simple_format(@character.abilities) %>
</p>

<% if @character.character_type == "Candidate" %>
<hr>
<strong>Candidate Information</strong><br>
<p>
  <strong>Color Preference:</strong>
  <%= @character.dragon_preference %>
  <br>
  <strong>Name Preferences:</strong>
  <%= @character.dragon_names %>
</p>
<% end %>

<% unless @character.craft.blank? %>
<hr>
<strong>Crafter Information</strong><br>
<p>
  <strong>Craft:</strong>
  <%= @character.craft %>
  <br>
  <strong>Rank:</strong>
  <%= @character.craft_rank %>
  <br>
  <strong>Specialty:</strong>
  <%= @character.craft_specialty %>
</p>
<p>
  <strong>Strengths/Weaknesses:</strong>
  <%= simple_format(@character.craft_abilities) %>
</p>
<% end %>

<% unless @character.hold.blank? %>
<hr>
<strong>Holder Information</strong><br>
<p>
  <strong>Hold:</strong>
  <%= @character.hold %>
  <br>
  <strong>Hold Size:</strong>
  <%= @character.hold_size %>
</p>
<% end %>

app/views/characters/_dragonriders.html.erb
<% @dragonriders = @characters %>

<% ["Gold", "Bronze", "Silver", "Brown", "Blue", "Green"].each do |color| %>
  <h2><%= color %></h2>
  <table class="char_table">
    <thead>
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= sortable "gender" %></th>
        <th><%= sortable "character_type", "Character Type" %></th>
        <th><%= sortable "craft" %></th>
        <th><%= sortable "rank" %></th>
        <th>Dragon</th>
        <th>Color</th>
        <th>Owner</th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <% if character.dragon && character.dragon.color == color %>
          <tr>
            <td class="char_data", id="name"><%= link_to character.name, character %></td>
            <td class="char_data", id="gender"><%= character.gender %></td>
            <td class="char_data", id="type"><%= link_to character.character_type, character_type_path(character.character_type) %></td>
            <td class="char_data", id="craft"><%= character.craft %></td>
            <td class="char_data", id="rank"><%= character.rank %></td>
            <td class="char_data", id="dragon_name"><%= character.dragon.name if character.dragon %></td>
            <td class="char_data", id="dragon_color"><%= character.dragon.color if character.dragon %></td>
            <td class="char_data", id="user"><%= link_to character.user.username, user_path(character.user.username) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <hr>
<% end %>

app/views/characters/_form.html.erb
<% if @character.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>

    <ul>
    <% @character.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= render 'rules' %>

<strong>Character Information:</strong><br><br>

<div class="field">
  <%= f.label(:category, "PC/NPC") %><br>
  <%= f.select :category, ["Primary", "Secondary", "NPC/TANPC"] %>
</div>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="field">
  <%= f.label :pronunciation %><br>
  <%= f.text_field :pronunciation %>
</div>
<div class="field">
  <%= f.label :age %><br>
  <%= f.number_field :age %>
</div>
<div class="field">
  <%= f.label(:character_type, "Character Type") %><br>
  <%= f.select :character_type, ['Candidate', 'Crafter', 'Dragonrider', 'Holder', 'Weyrling', 'Other'] %>
</div>
<div class="field">
  <%= f.label :rank %><br>
  <%= f.text_field :rank %>
</div>
<div class="field">
  <%= f.label :gender %><br>
  <%= f.select :gender, ['Male', 'Female'] %>
</div>
<div class="field">
  <%= f.label(:preference, "Sexual Preference") %><br>
  <%= f.select :preference, ['Asexual', 'Bisexual', 'Heterosexual', 'Homosexual', 'Unsure'] %>
</div>
<div class="field">
  <%= f.label :location %><br>
  <%= f.text_field :location %>
</div>
<div class="field">
  <%= f.label "Appearance" %><br>
  <%= f.text_area :description %>
</div>
<div class="field">
  <%= f.label :personality %><br>
  <%= f.text_area :personality %>
</div>
<div class="field">
  <%= f.label :history %><br>
  <%= f.text_area :history %>
</div>
<div class="field">
  <%= f.label(:abilities, "Abilities/Strengths/Weaknesses") %><br>
  <%= f.text_area :abilities %>
</div>

<hr>
<strong>Candidate Information:</strong> (Only fill in this if you wish your character to be considered for impression.)<br><br>
<div class="field">
  <%= f.label(:dragon_preference, "Dragon Color Preferences")%><br>
  <%= f.text_field :dragon_preference %>
</div>
<div class="field">
  <%= f.label(:dragon_names, "Dragon Names")%><br>
  <%= f.text_field :dragon_names %>
</div>

<hr>
<strong>Crafter Information:</strong> (Only fill in this if you wish your character is involved in a craft.)<br><br>
<div class="field">
  <%= f.label :craft %><br>
  <%= f.select :craft, ['Artist', 'Baker', 'Beastcraft', 'Chemist', 'Cobbler', 'Dolphineer', 'DragonHealer', 'Farmer', 'Fisher', 'Glasscrafter', 'Harper', 'Healer', 'Miner', 'Pirate', 'Runner', 'Sailor', 'Seacrafter', 'Smith', 'Tailor', 'Tanner', 'Vinter', 'Weaver', 'Woodcraft', 'Whercraft', 'Other'], include_blank: true %>
</div>
<div class="field">
  <%= f.label(:craft_rank, "Craft Rank")%><br>
  <%= f.select :craft_rank, ['Apprentice', 'Sr. Apprentice', 'Journeyman', 'Sr. Journeyman', 'Master', 'Craft Master'] %>
</div>
<div class="field">
  <%= f.label "Specialty"%><br>
  <%= f.text_field :craft_specialty %>
</div>
<div class="field">
  <%= f.label(:craft_abilities, "Strength/Weaknesses")%><br>
  <%= f.text_area :craft_abilities %>
</div>

<hr>
<strong>Holder Information:</strong> (Only fill in this if your character is affiliated with a hold.)<br><br>
<div class="field">
  <%= f.label :hold %><br>
  <%= f.text_field :hold %>
</div>
<div class="field">
  <%= f.label "Size" %><br>
  <%= f.text_field :hold_size %>
</div>

app/views/characters/_rules.html.erb
<p>
  Hi, everyone! First, some tips and guidelines:
</p>

<p>
  Once you submit this form, you should receive automated email. That means that we've received your character and will get back to you in 24 to 48 hours.
</p>

<p>
  Certain parts of the below form are required only for certain characters. For example, a candidate needs the candidate section filled out, along with the general character information, and any other sections appropriate to your character.
</p>

<p>
  <strong>Important Note: </strong> If you are creating a rider and/or a pet owner, a dragon form and/or pet form(s) <strong>must</strong> be filled out after you submit your character. You'll find the links at the bottom of your character sheet.
</p>

<p>
  If you have not joined our lists, please do so now. You can find them here: <%= link_to 'Exile Weyr OOC', 'https://groups.google.com/forum/#!forum/exile-weyr-ooc' %>, <%= link_to 'Exile_Weyr', 'https://groups.google.com/forum/#!forum/exile-weyr'%>
</p>

<p>
  If you need any assistance in filling out the persona sheet, contact the BoD. <%= link_to 'Here', article_path('character-creation-guide') %> is a sheet that tells you basically what we're looking for. And you're free to browse the uploaded and already approved sheets for examples. 
</p>

<p>
  Not sure if you want to start a character from scratch?  Want someone with a past already? Or need to know if someone already has a major rank you'd like to play, or need to RP out? Check out our <%= link_to "Adoptable and NPCs", article_path('adoptables-and-npcs') %> right here!
</p>

<h2>Rules to Remember</h2>

<p>
1. Don't forget about your firelizards- many people write them and then forget about them. You can always ask for a second metallic one later or gain one during game play. But no one persona should have more than four.
</p>

<p>
2. Try to avoid stereotypes or cliches. This goes for both personalities, appearances, and histories. We want original and interesting!
</p>

<p>
3. Try to write interesting characters. People aren't defined by their strengths but rather their limitations. Also, Pern is pastoral and there probably aren't a whole lot of people who are abused, abducted, or abandoned.
</p>

<p>
4. Please don't send me a half filled out form with parts not done. It is really a pain to have to send it back to you to have you redo the ones you missed. Example: If you are making a dragonrider, please use the Dragonrider Persona Sheet. You will find separate persona sections for Dragonriders, Crafters, Holders/Holderfolk, and NPC's. For those who have holdless or Caravan people, please use the Crafter Persona Sheet.  Also, please note many characters may need to have more than one section filled out. Many riders/candidates are crafters, too. Your writer name (screen-name) and email is a MUST. But remember, not all sections are needed for all characters. If you're unsure which sections you need.... ask! 
</p>

<p>
5. If you have a weyrling pair please put the size and their personality and strengths/weaknesses as you would for a full-grown dragon. What we are looking for is how they will be and what size they will be as adults. It is such a pain in the rear to keep changing the size and stuff as they "grow".
</p>

<p>
6. Please keep your personas as life like as possible. We don't need any Gods or superheros in here. This means give them flaws, physical or emotional. Give them things that make them HUMAN. 
</p>

<p>
7. Please, use pronounceable names, but 'Pernified' ones.  Please, we want better thought than K'mart or Wal'mart, or Betty and Sue.  However, we don't want Ketrichyocenianara. We'd like to be able to pronounce them, and not look it up every time we needed to write it out. Same rule of thumb goes for Dragons. Death, Truth? Meth? No, please. But neither Xiozayarianeth.  Believeable, please. 
</p>

<p>
8. No Carbon Copies. No Plagiarism. Characters from Anne's books are NOT allowed.  I don't mind characters from anime or movies or other books, but please try to make it your own. Please use a little creativity and originality. We're not going to be upset if you use someone for a basis, or pull inspiration from a few places. We will, though, send your sheet back to you if we find it's a carbon copy  of someone else's biography or if you've quoted text from books or anything, okay? This noted, this is a rule that is always in effect. If we approve a sheet and later find out it's plagiarized, we reserve the right to ask you to change it.  
</p>

<p>
9. Candidates with only one color preference. This isn't a no-no. I understand that sometimes,  you only want to play a character if it's with one particular color. And we'd rather Impress you to a color you want than have a candidate become a weyrling and then stop being played because you don't like the dragon's color. This is only a friendly reminder that if you mark 'gold only' or 'silver only' you may have to be prepared to wait a few hatchings to get one, and they'll need to be a fairly active and well-written character. 
</p>

<p>
10. Pay attention to age requirements, though we are pretty lax about this and if it's a point in a well-written sheet, we will waive this rule. 
</p>

<p>
For Crafters: 
</p>

<ul>
  <li>Apprentice - From age 12 and up.</li>
  <li>Journeyman/woman - 5 to 7 turns after beginning apprenticeship.</li>
  <li>Master - 8 to 10 turns after becoming a journeyman/woman.</li>
  <li>Craftmaster - 5 to 7 turns after becoming a master.</li>
</ul>

<p>
Candidates range from 10-25. All other characters have no age requirement- at this time- however please make it believable. 
</p>

<p>
11. Again, if you're not 100% certain about the character you want, take a gander at out <%= link_to 'Adoptables', article_path('adoptables-and-npcs') %>.  WHo knows?  You might find a character there whom you can flesh out and breath life into, and they usually come with ranks and other quirks built in!
</p>

<br><hr>

app/views/characters/_wings.html.erb
<% @dragonriders = @characters %>

<% ["Queen's Wing", "High Altitude Wing", "Mid Altitude Wing", "Low Altitude Wing", "Weyrling Wing"].each do |wing| %>
  <h2><%= wing %></h2>
  <table class="char_table">
    <thead>
      <tr>
        <th><%= sortable "name" %></th>
        <th><%= sortable "gender" %></th>
        <th><%= sortable "character_type", "Character Type" %></th>
        <th><%= sortable "craft" %></th>
        <th><%= sortable "rank" %></th>
        <th>Dragon</th>
        <th>Color</th>
        <th>Owner</th>
      </tr>
    </thead>

    <tbody>
      <% @characters.each do |character| %>
        <% if character.dragon && character.dragon.wing == wing %>
          <tr>
            <td class="char_data", id="name"><%= link_to character.name, character %></td>
            <td class="char_data", id="gender"><%= character.gender %></td>
            <td class="char_data", id="type"><%= link_to character.character_type, character_type_path(character.character_type) %></td>
            <td class="char_data", id="craft"><%= character.craft %></td>
            <td class="char_data", id="rank"><%= character.rank %></td>
            <td class="char_data", id="dragon_name"><%= character.dragon.name if character.dragon %></td>
            <td class="char_data", id="dragon_color"><%= character.dragon.color if character.dragon %></td>
            <td class="char_data", id="user"><%= link_to character.user.username, user_path(character.user.username) %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
  
  <hr>
<% end %>

app/views/characters/edit.html.erb
<% title "Editing Character" %>

<%= form_for(@character) do |f| %>
  <%= render :partial => 'form', :locals => {:f => f} %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', @character %>

app/views/characters/index.html.erb
<% title(params[:character_type] ? "#{params[:character_type]} List" : "Characters List") %>

<p> Below is a list of all the <%= params[:character_type] ? params[:character_type].downcase.pluralize : "characters" %> in alphabetical order. </p>
<p>
  Click here to see lists by character type: 
  <%= link_to "All", :character_type => nil %>, 
  <%= link_to "Candidates", :character_type => "Candidate" %>, 
  <%= link_to "Crafters", :character_type => "Crafter" %>, 
  <%= link_to "Holders", :character_type => "Holder" %>, 
  <%= link_to "Riders", :character_type => "Dragonrider" %>,
  <%= link_to "Weyrlings", :character_type => "Weyrling" %>, 
  <%= link_to "Others", :character_type => "Other" %>
</p>

<p>
  Alternatively, click here to see the dragonrider wing list:
  <%= link_to "Wings", :character_type => "Wings" %>
</p>

<hr>

<% if params[:character_type] == "Dragonrider" %>
  <%= render "dragonriders" %>
<% elsif params[:character_type] == "Wings" %>
  <%= render "wings" %>
<% else %>
  <%= render "list" %>
<% end %>

app/views/characters/new.html.erb
<%= title "New Character" %>

<% if params[:preview_button]%>

<div id="preview_character">
  <%= render 'character' %>

  <button id="show_form">
    Continue Editing?
  </button>
</div>



<% end %>

<%= form_for(@character) do |f| %>
  <% if params[:preview_button] %>
    <div class='hidden_character_form'> 
      <%= render :partial => 'form', :locals => {:f => f} %>
    </div>
  <% else %>
    <%= render :partial => 'form', :locals => {:f => f} %>
  <% end %>
  <div class="actions">
    <%= f.submit %>
    <%= f.submit "Preview", name: "preview_button" unless params[:preview_button] %>
    <span class='hidden_character_form'><%= f.submit "Preview", name: "preview_button" %></span>
  </div>
<% end %>

<%= link_to 'Back', characters_path %>

app/views/characters/new_created.html.erb
<% title "New Characters" %>

<p> Below is a list of all the characters added in the last two weeks. </p>
<hr>

<%= render "list" %>

app/views/characters/new_updated.html.erb
<% title "Recently Updated Characters" %>

<p> Below is a list of all the characters that were updated in the last two weeks. </p>
<hr>

<%= render "list" %>

app/views/characters/show.html.erb
<%= title @character.name %>

<%= render 'character'%>

<% if @character.relationships.count > 0 %>
  <hr>
  <p>
    Listing <%= @character.name %>'s relationships:
  </p>
  <ul>
    <% @character.relationships.group_by(&:relation_type).each do |relation_type, relationships| %>
      <li>
        <strong><%= relation_type %>: </strong>
        <%= map_relationships(relationships) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @character.dragon %>
  <hr>
  <p>
    <strong>Information about <%= @character.name %>'s dragon</strong>
  </p>
  
  <p>
    <strong>Name:</strong>
    <%= @character.dragon.name %>
    <% if signed_in? %> 
      <% if is_admin? || is_current_user?(@character.user) %>
        ( <%= link_to 'Edit', edit_character_dragon_path(@character.name, @character.dragon) %> |
        <%= link_to 'Delete', character_dragon_path(@character.name, @character.dragon), method: :delete, data: { confirm: 'Are you sure?' } %> )
      <% end %>
    <% end %>
    <br>
    <strong>Color:</strong>
    <%= @character.dragon.color %>
    <br>
    <strong>Age:</strong>
    <%= @character.dragon.age %>
    <br>
    <strong>Size:</strong>
    <%= @character.dragon.size %>
    <% if @character.dragon.wing %>
      <br>
      <strong>Wing:</strong>
      <%= @character.dragon.wing %>
    <% end %>
  </p>
  
  <p>
    <strong>Appearance:</strong>
    <%= simple_format(@character.dragon.description) %>
  </p>

  <p>
    <strong>Personality:</strong>
    <%= simple_format(@character.dragon.personality) %>
  </p>

  <p>
    <strong>Strength/Weaknesses:</strong>
    <%= simple_format(@character.dragon.abilities) %>
  </p>
<% end %>


<% if @character.pets.count > 0 %>
  <hr>
  <p>
    <strong>Information about <%= @character.name %>'s <%= pluralize(@character.pets.count, "pet")%></strong>
  </p>
<% end %>

<% @character.pets.each do |pet| %>

  <p>
    <strong>Name:</strong>
    <%= pet.name %> 
    <% if signed_in? %>
      <% if is_admin? || is_current_user?(@character.user) %>
      ( <%= link_to 'Edit', edit_character_pet_path(@character.name, pet) %> |
      <%= link_to 'Delete', character_pet_path(@character.name, pet), method: :delete, data: { confirm: 'Are you sure?' } %> )
      <% end %>
    <% end %>
    <br>
    <strong>Type:</strong>
    <%= pet.pet_type %>
  </p>
  
  <p>
    <strong>Appearance:</strong>
    <%= simple_format(pet.description) %>
  </p>

  <p>
    <strong>Personality:</strong>
    <%= simple_format(pet.personality) %>
  </p>

<% end %>

<hr>
<center>
  <p>
    <% if signed_in? %>
      <% if is_admin? || is_current_user?(@character.user) %>

        |<%= link_to 'Edit Character', edit_character_path(@character.name) %> |
        <%= link_to 'Add Relationships', new_character_relationship_path(@character.name) %> |
        <%= link_to 'Edit Relationships', edit_character_relationships_path(@character.name)%> |
        <% unless @character.dragon %>
          <%= link_to 'Add Dragon', new_character_dragon_path(@character.name) %> | 
        <% end %>

        <%= link_to 'Add Pet', new_character_pet_path(@character.name) %> | 
        <%= link_to 'Upload Picture', upload_picture_path(@character)%>
      
      <% end %>
    <% end %>
    |<%= link_to "See more of #{@character.user.username}'s characters", user_path(@character.user) %> |
  </p>
</center>

app/views/characters/upload_picture.html.erb
<%= title "Upload Picture" %>

<% if @character.picture %>
  <p>
    <%= @character.name %>'s current picture:
    <center>
      <%= image_tag(@character.picture) %>
    </center>
  </p>
  <hr>
<% end %>

<p>
  Upload a new picture for <%= @character.name %> here.
</p>

<%= form_tag({url: upload_picture_path(@character), method: :get}, multipart: true) do %>
  <p>
    <%= label_tag :picture, "Upload this file:"%>
    <%= file_field_tag :picture %>
    <%= submit_tag "Send File", name: nil %>
  </p>
<% end %>

<p>
  <%= link_to "Back to #{@character.name}'s page", character_path(@character)%>
</p>