config/routes.rb
HelloWorld::Application.routes.draw do

  

  resources :clutches do
    resources :posts
    resources :eggs
  end

  match 'characters/:character_id/relationships/edit' => 'relationships#edit', :as => 'edit_character_relationships', via: :get
    
  resources :characters do
    resources :dragons
    resources :pets
    resources :relationships
  end
  
  resources :users
  resources :sessions
  resources :searches
  resources :articles
  
  match 'welcome' => 'articles#welcome', :as => 'welcome', via: :get
  
  root to: 'articles#welcome'
  
  match 'character_groups/:character_type' => 'characters#index', :as => 'character_type', via: :get
  match 'recent_characters' => 'characters#new_created', :as => 'recent_characters', via: :get
  match 'updated_characters' => 'characters#new_updated', :as => 'updated_characters', via: :get
  match 'set_status/:id' => 'characters#set_status', :as => 'set_status', via: [:get, :put]
  match 'approve_character/:id' => 'characters#approve_character', :as => 'approve_character', via: [:get, :put]
  match 'characters/:id/upload_picture' => 'characters#upload_picture', :as => 'upload_picture', via: [:get, :post]
  
  match 'approve_clutch/:id' => 'clutches#approve_clutch', :as => 'approve_clutch', via: [:get, :put]
  match 'start_hatching/:id' => 'clutches#start_hatching', :as => 'start_hatching', via: [:get, :put]
  
  match 'signup' => 'users#new', via: :get
  match 'signin' => 'sessions#new', via: :get
  match 'signout' => 'sessions#destroy', via: :delete
  match 'authenticate' => 'sessions#edit', via: :get
  
  match 'set_password/:id' => 'users#set_password', :as => 'set_password', via: [:get, :put]

  

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :clutch
  has_many :eggs
  
  default_scope { order("id ASC")}
  
  def show_post
    self.reveal = true
    self.save
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  before_action :set_clutch
  before_action :set_post, only: [:edit, :update, :destroy]
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:new, :create, :edit, :update, :destroy]
  

  # GET /posts
  # GET /posts.json
  def index
    @posts = @clutch.posts
  end

  # GET /posts/new
  def new
    @post = @clutch.posts.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = @clutch.posts.new(post_params)

    if @post.save
      redirect_to clutch_posts_path(@clutch), notice: 'Hatching post was successfully created.'
    else
      render action: 'new'
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    if @post.update(post_params)
      redirect_to redirect_to clutch_posts_path(@clutch), notice: 'Hatching post was successfully updated.'
    else
      render action: 'edit'
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to clutch_posts_path(@clutch)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :post_body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for([@clutch, @post]) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this egg from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label(:post_body, "Body") %><br>
    <%= f.text_area :post_body %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% title "Edit #{@post.title}"%>

<%= render 'form' %>

<%= link_to 'Back', @clutch %>

app/views/posts/index.html.erb
<%= title "#{@clutch.dame}'s Clutch, Clutched #{@clutch.date_clutched}" %>

<center>
<p>
  <strong>Dame:</strong>
  <%= "#{@clutch.dame_color} #{@clutch.dame}" %>
</p>

<p>
  <strong>Sire:</strong>
  <%= "#{@clutch.sire_color} #{@clutch.sire}" %>
</p>

<p>
  <strong>Date clutched:</strong>
  <%= @clutch.date_clutched %>
</p>

<p>
  <strong>Date hatched:</strong>
  <%= @clutch.date_hatched %>
</p>

  <% if @clutch.date_hatched < (Time.now - 1.day) %>
    <p>
      <strong>Clutch Theme:</strong>
      <%= @clutch.theme %>
    </p>
    
  <% elsif signed_in?%>
    <% if is_admin? || is_current_user?(@clutch.user) %>
      <p>
        <strong>Clutch Theme:</strong>
        <%= @clutch.theme %>
      </p>
    <% end %>
  <% end %>

<%if signed_in? && is_admin? && @posts.last %>
  <% unless @posts.last.reveal %>
    <p>
      <%= link_to "Start Hatching", start_hatching_path(@clutch) %>
    </p>
  <% end %>
<% end %>

</center>
<h2>Hatching Posts</h2>
<% if signed_in? %>
  <% @posts.each do |post| %>
    <% if is_admin? || post.reveal %>
      <h2>
        <%= post.title %>
        <% if signed_in? %>
          <% if is_admin? || is_current_user?(@clutch.user) %>
          <small>( <%= link_to 'Edit', edit_clutch_post_path(@clutch, post) %> | <%= link_to 'Delete', clutch_post_path(@clutch, post), method: :delete, data: { confirm: 'Are you sure?' } %> )</small>
          <% end %>
        <% end %>
      </h2>

      <p>
        <%= simple_format(post.post_body) %>
      </p>
    <% end %>
  <% end %>
<% else %>
<center>
  <p>This content is only available for registered users. Please sign in or  sign up (link above) to view this content. Thanks!</p>
</center>  
<% end %>

<center>
  <p>
    <% if signed_in? %>
      <% if is_admin? || is_current_user?(@clutch.user) %>
        |<%= link_to 'New Hatching Post', new_clutch_post_path %>
      <% end %>
    <% end %>
    |<%= link_to "Back to Egg Descriptions", @clutch %> |
    <%= link_to "Back to All Clutches", clutches_path %> |
  </p>
</center>

app/views/posts/new.html.erb
<% title "Add a New Hatching Post"%>

<%= render 'form' %>

<%= link_to 'Back', @clutch %>